### PR TITLE
file.c

### PR DESCRIPTION
**Pull request by yashrana1974**

### CODE REVIEW

**Comment by krishvsoni** [comment]
heyy Yash, please commit one more time

**Comment by yashrana1974** [comment]
Okay 👍

**Comment by yashrana1974** [comment]
Where to add #10

**Comment by yashrana1974** [comment]
I have done please check it out I have added number1=10;

**Comment by krishvsoni** [comment]
Yess I got it, but many people are committing the same change that's why do it one more time then I will merge ..

**Comment by yashrana1974** [comment]
Ok, no problem.

**Comment by yashrana1974** [comment]
I have now added number2=20; please check it out

**Comment by krishvsoni** [comment]
Yess I can see your change. Now do pull request!!

**Comment by yashrana1974** [comment]
Yeah I did pull request from vs code terminal

**Comment by krishvsoni** [comment]
After git push
Got to GitHub repository on your browser and then do pull request.

**Comment by yashrana1974** [comment]
Ok, I will try. Sorry my phone's battery was low

**Comment by yashrana1974** [comment]
I have done it please check it.

**Pull request merged**
